#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon.sh" in your plugin-archive. It will be renamed to NAME
# during installation

pluginname=$(basename $0 .sh)

if [ -x /usr/bin/logger ]; then
    /usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from RCSwitch Plugin"
fi

# Create sudoers file
if [ -x /usr/bin/logger ]; then 
	/usr/bin/logger "loxberry-plugin-$pluginname - Adding sudoers permissions"
fi
chmod 0640 /etc/sudoers.d/$pluginname
echo %loxberry ALL = NOPASSWD: REPLACEINSTALLFOLDER/data/plugins/$pluginname/bin/send433 > /etc/sudoers.d/$pluginname
echo %loxberry ALL = NOPASSWD: /etc/init.d/pilight >> /etc/sudoers.d/$pluginname
chmod 0440 /etc/sudoers.d/$pluginname
chmod 0755 REPLACEINSTALLFOLDER/data/plugins/$pluginname/bin/send433

# Installing pilight
if [ ! -x /usr/local/sbin/pilight-daemon ]; then
  if [ -x /usr/bin/logger ]; then 
	/usr/bin/logger "loxberry-plugin-$pluginname - Installing pilight - please be patient..."
  fi
  cd /tmp
  wget http://apt.pilight.org/pool/stable/main/l/libmbedx509-0/libmbedx509-0_2.6.0-1_armhf.deb
  wget http://apt.pilight.org/pool/stable/main/l/libmbedtls10/libmbedtls10_2.6.0-1_armhf.deb
  wget http://apt.pilight.org/pool/stable/main/l/libmbedcrypto0/libmbedcrypto0_2.6.0-1_armhf.deb
  dpkg -i libmbed*.deb
  rm libmbed*.deb
  echo "deb http://apt.pilight.org/ stable main" > /etc/apt/sources.list.d/pilight.list
  /usr/bin/wget -O - http://apt.pilight.org/pilight.key | apt-key add -
  /usr/bin/apt-get update
  /usr/bin/apt-get -y install pilight
fi

# Configure pilight
if [ -x /usr/bin/logger ]; then 
	/usr/bin/logger "loxberry-plugin-$pluginname - Configuring pilight"
fi

service pilight stop

if [ -d /etc/pilight ] && [ ! -L /etc/pilight ]; then
  mv /etc/pilight /etc/pilight.orig
fi
rm -rf /etc/pilight
ln -s REPLACEINSTALLFOLDER/config/plugins/$pluginname/pilight /etc/pilight

# Add new parameter gpio-platform if not exist
if  ! grep -q "gpio-platform" REPLACEINSTALLFOLDER/config/plugins/$pluginname/pilight/config.json
then
	sed -i 's#"port": 5000,#"port": 5000,\n\t\t"gpio-platform": "none",#g' REPLACEINSTALLFOLDER/config/plugins/$pluginname/pilight/config.json
	sed -i 's#"port": 5000#"port": 5000,\n\t\t"gpio-platform": "none"#g' REPLACEINSTALLFOLDER/config/plugins/$pluginname/pilight/config.json
fi

# ini parser from https://www.joedog.org/2015/02/13/sh-script-ini-parser/
# and http://mark.aufflick.com/blog/2007/11/08/parsing-ini-files-with-sed
iniparser() {
    INI_FILE=$1
    INI_SECTION=$2
    eval `sed -e 's/[[:space:]]*\=[[:space:]]*/=/g' \
        -e 's/;.*$//' \
        -e 's/[[:space:]]*$//' \
        -e 's/^[[:space:]]*//' \
        -e "s/^\(.*\)=\([^\"']*\)$/$INI_SECTION\1=\"\2\"/" \
        < $INI_FILE \
        | sed -n -e "/^\[$INI_SECTION\]/,/^\s*\[/{/^[^;].*\=.*/p;}"`
}
 
iniparser REPLACEINSTALLFOLDER/config/plugins/$pluginname/RCSwitch.cfg "general"

if [ $generalStartPilightd -eq "1" ]; then 
	service pilight start
fi

# Installing WiringPi on LoxBerry 2.0
if [ ! -x /usr/bin/gpio ]; then
  if [ -x /usr/bin/logger ]; then
        /usr/bin/logger "loxberry-plugin-$pluginname - Installing WiringPi - please be patient..."
  fi
  cd /tmp
  wget https://project-downloads.drogon.net/wiringpi-latest.deb
  dpkg -i wiringpi-latest.deb
  rm wiringpi-latest.deb
fi

exit 0
